-- MX Sentinel — PostgreSQL schema (operational / configuration system-of-record)
--
-- Scope: tenants, users, API credentials, notification channels, domains,
-- versioned DNS snapshots + findings, IP pools, relay nodes, alert rules + events.
--
-- Telemetry does NOT live here — high-volume SMTP events go to ClickHouse
-- (see schemas/clickhouse/001_smtp_telemetry.sql). This store holds slowly-changing
-- relational truth.
--
-- Conventions:
--   * UUID primary keys. UUIDv7 is generated by the application for time-sortability;
--     gen_random_uuid() is the DB-side default fallback.
--   * timestamptz everywhere; store UTC.
--   * Every tenant-scoped table carries tenant_id and is designed for row-level security.
--   * Enumerated values use Postgres ENUM types for integrity + compactness.

CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS citext;     -- case-insensitive email / domain

-- ---------------------------------------------------------------------------
-- Enum types
-- ---------------------------------------------------------------------------
CREATE TYPE tenant_status      AS ENUM ('active', 'suspended', 'trial', 'closed');
CREATE TYPE tenant_kind        AS ENUM ('hosting_provider', 'msp', 'enterprise');
CREATE TYPE user_role          AS ENUM ('owner', 'admin', 'operator', 'viewer');
CREATE TYPE user_status        AS ENUM ('active', 'invited', 'disabled');
CREATE TYPE domain_status      AS ENUM ('pending_verification', 'monitored', 'paused', 'error');
CREATE TYPE dns_finding_sev    AS ENUM ('info', 'warning', 'critical');
CREATE TYPE dns_category       AS ENUM (
    'spf', 'dkim', 'dmarc', 'mx', 'ptr', 'a_aaaa',
    'dnssec', 'mta_sts', 'tls_rpt', 'smtp_tls', 'bimi', 'arc'
);
CREATE TYPE ip_pool_purpose    AS ENUM ('transactional', 'marketing', 'warmup', 'mixed');
CREATE TYPE channel_kind       AS ENUM ('email', 'slack', 'webhook', 'pagerduty');
CREATE TYPE alert_signal       AS ENUM (
    'dns_breakage', 'rejection_spike', 'blacklist_hit',
    'tls_failure', 'complaint_spike', 'bounce_rate'
);
CREATE TYPE alert_state        AS ENUM ('open', 'acknowledged', 'resolved', 'muted');

-- ---------------------------------------------------------------------------
-- Tenancy
-- ---------------------------------------------------------------------------
CREATE TABLE tenants (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name          TEXT          NOT NULL,
    slug          CITEXT        NOT NULL UNIQUE,
    kind          tenant_kind   NOT NULL DEFAULT 'enterprise',
    status        tenant_status NOT NULL DEFAULT 'trial',
    settings      JSONB         NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE TABLE users (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    email         CITEXT      NOT NULL,
    display_name  TEXT,
    role          user_role   NOT NULL DEFAULT 'viewer',
    status        user_status NOT NULL DEFAULT 'invited',
    -- AuthN secrets (password hash / SSO subject) are stored hashed or via IdP, never plaintext.
    password_hash TEXT,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, email)
);

-- API tokens: only the hash is stored. The plaintext token is shown once at creation.
CREATE TABLE api_credentials (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name          TEXT        NOT NULL,
    token_prefix  TEXT        NOT NULL,            -- non-secret, for display & lookup
    token_hash    TEXT        NOT NULL,            -- e.g. argon2/sha256 of the secret
    scopes        TEXT[]      NOT NULL DEFAULT '{}',
    created_by    UUID        REFERENCES users(id) ON DELETE SET NULL,
    last_used_at  TIMESTAMPTZ,
    expires_at    TIMESTAMPTZ,
    revoked_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);
CREATE INDEX idx_api_credentials_prefix ON api_credentials (token_prefix);

CREATE TABLE notification_channels (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    kind          channel_kind NOT NULL,
    name          TEXT         NOT NULL,
    -- Channel config (webhook URL, slack token ref, etc.). Secrets stored as references
    -- to Vault/KMS, not raw values. See docs/data-model.md privacy/security notes.
    config        JSONB        NOT NULL DEFAULT '{}'::jsonb,
    enabled       BOOLEAN      NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);

-- ---------------------------------------------------------------------------
-- Domains
-- ---------------------------------------------------------------------------
CREATE TABLE domains (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           UUID          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name                CITEXT        NOT NULL,           -- FQDN, e.g. example.com
    status              domain_status NOT NULL DEFAULT 'pending_verification',
    verification_token  TEXT,
    verified_at         TIMESTAMPTZ,
    check_interval_secs INTEGER       NOT NULL DEFAULT 300 CHECK (check_interval_secs >= 60),
    last_checked_at     TIMESTAMPTZ,
    created_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);
CREATE INDEX idx_domains_tenant ON domains (tenant_id);

-- ---------------------------------------------------------------------------
-- DNS snapshots (versioned, timestamped) — the root-cause-correlation differentiator.
-- One row per *change*: a new snapshot is written only when `checksum` differs from the
-- domain's previous snapshot, so every change is preserved with its time but storage is bounded.
-- ---------------------------------------------------------------------------
CREATE TABLE dns_snapshots (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    domain_id     UUID        NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
    captured_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Full parsed DNS state at capture time (all record types), keyed by category.
    state         JSONB       NOT NULL,
    -- Content checksum of `state` for change detection.
    checksum      TEXT        NOT NULL,
    -- Convenience rollup of overall health for fast dashboard reads.
    is_healthy    BOOLEAN     NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_dns_snapshots_domain_time ON dns_snapshots (domain_id, captured_at DESC);

CREATE TABLE dns_findings (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    snapshot_id   UUID            NOT NULL REFERENCES dns_snapshots(id) ON DELETE CASCADE,
    domain_id     UUID            NOT NULL REFERENCES domains(id) ON DELETE CASCADE,
    category      dns_category    NOT NULL,
    severity      dns_finding_sev NOT NULL,
    code          TEXT            NOT NULL,   -- stable machine code, e.g. SPF_LOOKUP_LIMIT
    message       TEXT            NOT NULL,   -- human-readable
    detail        JSONB           NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now()
);
CREATE INDEX idx_dns_findings_snapshot ON dns_findings (snapshot_id);
CREATE INDEX idx_dns_findings_domain_sev ON dns_findings (domain_id, severity);

-- ---------------------------------------------------------------------------
-- Relay infrastructure & IP pools
-- ---------------------------------------------------------------------------
CREATE TABLE ip_pools (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID            NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name          TEXT            NOT NULL,
    purpose       ip_pool_purpose NOT NULL DEFAULT 'mixed',
    addresses     INET[]          NOT NULL DEFAULT '{}',
    warmup_stage  INTEGER,                    -- nullable; set while warming
    created_at    TIMESTAMPTZ     NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);

CREATE TABLE relay_nodes (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID        REFERENCES tenants(id) ON DELETE CASCADE,  -- nullable: shared relays
    hostname      TEXT        NOT NULL,
    primary_ip    INET,
    ip_pool_id    UUID        REFERENCES ip_pools(id) ON DELETE SET NULL,
    software      TEXT,                        -- 'postfix' | 'powermta' | 'haraka'
    last_seen_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (hostname)
);

-- ---------------------------------------------------------------------------
-- Alerting (rules + firings)
-- ---------------------------------------------------------------------------
CREATE TABLE alert_rules (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID         NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name          TEXT         NOT NULL,
    signal        alert_signal NOT NULL,
    -- Condition is a structured predicate over telemetry/DNS/reputation, e.g.
    -- {"metric":"rejection_rate","provider":"microsoft","op":">","threshold":0.05,"window_secs":900}
    condition     JSONB        NOT NULL,
    -- Channels to notify on fire (FK ids in notification_channels).
    channel_ids   UUID[]       NOT NULL DEFAULT '{}',
    enabled       BOOLEAN      NOT NULL DEFAULT true,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);
CREATE INDEX idx_alert_rules_tenant ON alert_rules (tenant_id) WHERE enabled;

CREATE TABLE alert_events (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    rule_id       UUID        NOT NULL REFERENCES alert_rules(id) ON DELETE CASCADE,
    state         alert_state NOT NULL DEFAULT 'open',
    triggered_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at   TIMESTAMPTZ,
    -- Snapshot of the data that tripped the rule + any correlation pointers (event_ids).
    payload       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_alert_events_tenant_time ON alert_events (tenant_id, triggered_at DESC);
CREATE INDEX idx_alert_events_open ON alert_events (tenant_id) WHERE state = 'open';

-- ---------------------------------------------------------------------------
-- DMARC report archive pointers (raw XML lives in object storage; this is the index)
-- ---------------------------------------------------------------------------
CREATE TABLE dmarc_reports (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    domain_id     UUID        REFERENCES domains(id) ON DELETE SET NULL,
    org_name      TEXT,                         -- reporting org (e.g. google.com)
    report_id     TEXT,                         -- <report_metadata><report_id>
    date_begin    TIMESTAMPTZ,
    date_end      TIMESTAMPTZ,
    object_key    TEXT        NOT NULL,         -- s3://.../dmarc-raw/...
    record_count  INTEGER     NOT NULL DEFAULT 0,
    ingested_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, org_name, report_id)
);
CREATE INDEX idx_dmarc_reports_domain_time ON dmarc_reports (domain_id, date_begin DESC);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tenants_updated   BEFORE UPDATE ON tenants    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_users_updated     BEFORE UPDATE ON users      FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_domains_updated   BEFORE UPDATE ON domains    FOR EACH ROW EXECUTE FUNCTION set_updated_at();
CREATE TRIGGER trg_alertrules_updated BEFORE UPDATE ON alert_rules FOR EACH ROW EXECUTE FUNCTION set_updated_at();
