-- MX Sentinel — PostgreSQL reference DDL: viewer-facing hostname aliases.
--
-- Runnable migration: migrations/postgres/00029_viewer_domain_aliases.sql (keep in sync).
--
-- Stable aliases that hide provider-owned hostnames from viewer-role sessions.
--
-- The dashboard is served white-label on more than one domain (MXS_EXTRA_DOMAINS, see
-- deploy/Caddyfile), and on the white-label domain a viewer must not be able to tell who
-- operates the relay. But the provider's own hostnames are woven through the telemetry —
-- sending domains, SASL usernames, DMARC sources, incident titles — so they cannot simply
-- be filtered out without emptying the product.
--
-- Instead apid rewrites them on the way out (internal/api/mask.go), and this table holds
-- the mapping so a given hostname always presents as the SAME alias: across endpoints,
-- across requests, and across restarts. Without persistence a viewer would see one server
-- appear under different names on two pages, or under a new name tomorrow, which is worse
-- than showing the real one.
--
-- Rows are assigned on first sight and never reused. seq drives the human-readable label
-- (relay-01, relay-02, …) so the aliases read like infrastructure rather than hashes.
-- The mapping is a presentation concern only: nothing else joins against it, and deleting
-- a row just means the next sighting mints a fresh alias.

CREATE TABLE viewer_domain_aliases (
    real_host  TEXT        PRIMARY KEY,
    seq        INTEGER     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (seq)
);
