#!/bin/bash
#
# MX Sentinel cPanel/WHM plugin installer. Run as root ON the WHM/cPanel server.
#
#   ./install.sh --bin ./mxsentinel-plugin --api-base https://api.you.com --token mxs_...
#
# Flags:
#   --bin PATH        Path to the mxsentinel-plugin binary (built for this server's OS/arch).
#   --api-base URL    MX Sentinel apid base URL.        (or env MXS_API_BASE)
#   --token TOKEN     Tenant API token with ADMIN scope (provisions the relay SMTP user).
#                     (or env MXS_API_TOKEN)
#   --no-verify-ssl   Disable TLS verification to apid (self-signed/internal CA).
#   --whm-only        Install only the WHM admin plugin.
#   --user-only       Install only the cPanel end-user plugin.
#   --keep-config     Do not overwrite an existing /etc/mxsentinel/plugin.conf.
#
set -euo pipefail

BIN_SRC=""
API_BASE="${MXS_API_BASE:-}"
API_TOKEN="${MXS_API_TOKEN:-}"
VERIFY_SSL="true"
DO_WHM=1
DO_USER=1
KEEP_CONFIG=0

while [ $# -gt 0 ]; do
  case "$1" in
    --bin) BIN_SRC="$2"; shift 2;;
    --api-base) API_BASE="$2"; shift 2;;
    --token) API_TOKEN="$2"; shift 2;;
    --no-verify-ssl) VERIFY_SSL="false"; shift;;
    --whm-only) DO_USER=0; shift;;
    --user-only) DO_WHM=0; shift;;
    --keep-config) KEEP_CONFIG=1; shift;;
    *) echo "unknown flag: $1" >&2; exit 2;;
  esac
done

[ "$(id -u)" = "0" ] || { echo "must run as root" >&2; exit 1; }
[ -d /usr/local/cpanel ] || { echo "this does not look like a cPanel/WHM server (/usr/local/cpanel missing)" >&2; exit 1; }

HERE="$(cd "$(dirname "$0")" && pwd)"
BINDEST="/usr/local/bin/mxsentinel-plugin"
CONFDIR="/etc/mxsentinel"
CONF="$CONFDIR/plugin.conf"
SOCKET_DIR="/run/mxsentinel-plugin"

# --- locate the binary ---------------------------------------------------------
if [ -z "$BIN_SRC" ]; then
  for c in "$HERE/mxsentinel-plugin" "$HERE/../../bin/mxsentinel-plugin" "./mxsentinel-plugin"; do
    [ -x "$c" ] && BIN_SRC="$c" && break
  done
fi
[ -n "$BIN_SRC" ] && [ -f "$BIN_SRC" ] || {
  echo "binary not found. Build it for this server:" >&2
  echo "  GOOS=linux GOARCH=amd64 go build -o mxsentinel-plugin ./cmd/cpanel-plugin" >&2
  echo "then re-run with --bin ./mxsentinel-plugin" >&2
  exit 1
}

echo "==> installing binary -> $BINDEST"
install -m 0755 "$BIN_SRC" "$BINDEST"

# --- config --------------------------------------------------------------------
mkdir -p "$CONFDIR"; chmod 0755 "$CONFDIR"
if [ -f "$CONF" ] && [ "$KEEP_CONFIG" = "1" ]; then
  echo "==> keeping existing $CONF"
else
  if [ -z "$API_BASE" ]; then read -r -p "MX Sentinel API base URL: " API_BASE; fi
  if [ -z "$API_TOKEN" ]; then read -r -p "Tenant API token (mxs_..., ADMIN scope): " API_TOKEN; fi
  [ -n "$API_BASE" ] && [ -n "$API_TOKEN" ] || { echo "api-base and token are required" >&2; exit 1; }
  echo "==> writing $CONF (root-only)"
  umask 077
  cat > "$CONF" <<EOF
# Generated by plugins/cpanel/install.sh — keep this file root-only (0600).
api_base = ${API_BASE%/}
token = $API_TOKEN
verify_ssl = $VERIFY_SSL
socket_path = $SOCKET_DIR/api.sock
EOF
  chmod 0600 "$CONF"
fi

# --- broker daemon (systemd) ----------------------------------------------------
echo "==> installing systemd unit"
install -m 0644 "$HERE/systemd/mxsentinel-plugin.service" /etc/systemd/system/mxsentinel-plugin.service
systemctl daemon-reload
systemctl enable --now mxsentinel-plugin.service
sleep 1
systemctl is-active --quiet mxsentinel-plugin.service \
  && echo "    broker active" \
  || { echo "    broker failed to start — check: journalctl -u mxsentinel-plugin" >&2; }

# --- CageFS (CloudLinux): expose the socket dir inside user cages ---------------
if command -v cagefsctl >/dev/null 2>&1; then
  echo "==> CageFS detected — exposing $SOCKET_DIR inside user cages"
  if ! grep -qxF "$SOCKET_DIR" /etc/cagefs/cagefs.mp 2>/dev/null; then
    echo "$SOCKET_DIR" >> /etc/cagefs/cagefs.mp
  fi
  cagefsctl --remount-all >/dev/null 2>&1 || \
    echo "    NOTE: 'cagefsctl --remount-all' failed; run it manually so users can reach the socket." >&2
fi

# --- WHM admin plugin -----------------------------------------------------------
if [ "$DO_WHM" = "1" ]; then
  echo "==> installing WHM admin plugin"
  WHMCGI=/usr/local/cpanel/whostmgr/docroot/cgi/mxsentinel
  mkdir -p "$WHMCGI"
  install -m 0755 "$HERE/whm/index.cgi" "$WHMCGI/index.cgi"
  /usr/local/cpanel/bin/register_appconfig "$HERE/whm/mxsentinel.conf" \
    && echo "    registered in WHM (search 'MX Sentinel' in the WHM sidebar)" \
    || echo "    register_appconfig failed — register manually." >&2
fi

# --- cPanel end-user plugin -----------------------------------------------------
if [ "$DO_USER" = "1" ]; then
  echo "==> installing cPanel user plugin"
  for THEME in jupiter; do
    BASE="/usr/local/cpanel/base/frontend/$THEME"
    [ -d "$BASE" ] || continue
    PDIR="$BASE/mxsentinel"
    mkdir -p "$PDIR"
    install -m 0755 "$HERE/user/index.live.cgi" "$PDIR/index.live.cgi"
    # Icon: ship one as plugins/cpanel/user/mxsentinel.png, else drop a placeholder.
    if [ -f "$HERE/user/mxsentinel.png" ]; then
      install -m 0644 "$HERE/user/mxsentinel.png" "$PDIR/mxsentinel.png"
    else
      printf 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+M8AAAMCAQDc7v9aAAAAAElFTkSuQmCC' \
        | base64 -d > "$PDIR/mxsentinel.png" 2>/dev/null || true
    fi
    install -m 0644 "$HERE/user/dynamicui_mxsentinel.conf" "$BASE/dynamicui/dynamicui_mxsentinel.conf"
    echo "    installed into theme: $THEME"
  done
  /usr/local/cpanel/bin/rebuild_sprites jupiter >/dev/null 2>&1 || true
  echo "    users will see 'MX Sentinel' under the Email group (re-login may be needed)"
fi

echo
echo "Done. Verify the broker can reach apid:"
echo "    curl --unix-socket $SOCKET_DIR/api.sock http://x/healthz   # expect HTTP 200"
echo "    journalctl -u mxsentinel-plugin -n 30"
