-- +goose Up
-- Inbox-placement / seed-list testing (internal/seedtest, cmd/seedd).
--
-- A "seed list" is a per-tenant collection of seed mailboxes across providers (Gmail,
-- Outlook, Yahoo, ...). A "seed run" sends a uniquely-tagged synthetic probe message to
-- each seed address, then a collector (IMAP poll of the seed inboxes) records whether the
-- probe landed in the inbox, the spam/junk folder, or went missing. Aggregating the
-- per-seed results yields inbox/spam/missing placement percentages per provider — the
-- GlockApps/Litmus-style capability.
--
-- Privacy: probe messages are SYNTHETIC test content generated by MX Sentinel. Only our own
-- tagged probes are ever read from the seed mailboxes; no real user mail is ingested. IMAP
-- credentials for the seed mailboxes are NOT stored here — they come from seedd's environment
-- config (internal/seedtest.LoadConfig), keyed by seed address.

-- seed_lists: one row per named seed list under a tenant.
CREATE TABLE seed_lists (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id   UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name        TEXT        NOT NULL,
    description TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, name)
);
CREATE INDEX idx_seed_lists_tenant ON seed_lists (tenant_id);

-- seed_addresses: seed mailboxes belonging to a list, each tagged with its provider.
CREATE TABLE seed_addresses (
    id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id  UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    list_id    UUID        NOT NULL REFERENCES seed_lists(id) ON DELETE CASCADE,
    address    TEXT        NOT NULL,
    provider   TEXT        NOT NULL DEFAULT 'other', -- gmail, outlook, yahoo, other
    enabled    BOOLEAN     NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (list_id, address)
);
CREATE INDEX idx_seed_addresses_list ON seed_addresses (list_id);
CREATE INDEX idx_seed_addresses_tenant ON seed_addresses (tenant_id);

-- seed_runs: one execution of a seed list. run_tag is a short unique token that appears in
-- every probe of the run (X-header prefix + plus-address label) so results can be correlated.
--
-- Status lifecycle:
--   pending    - run created, probes not yet sent
--   sending    - probes are being delivered to seeds
--   collecting - all probes sent; polling seed mailboxes for placement
--   completed  - every result resolved (inbox/spam/missing) or the collection window elapsed
--   failed     - the run could not be sent
CREATE TABLE seed_runs (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id    UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    list_id      UUID        REFERENCES seed_lists(id) ON DELETE SET NULL,
    name         TEXT        NOT NULL DEFAULT '',
    run_tag      TEXT        NOT NULL,
    from_address TEXT        NOT NULL DEFAULT '',
    ip_pool      TEXT        NOT NULL DEFAULT '',
    status       TEXT        NOT NULL DEFAULT 'pending',
    seed_count   INTEGER     NOT NULL DEFAULT 0,
    sent_count   INTEGER     NOT NULL DEFAULT 0,
    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, run_tag)
);
CREATE INDEX idx_seed_runs_tenant_status ON seed_runs (tenant_id, status);
CREATE INDEX idx_seed_runs_status ON seed_runs (status);

-- seed_results: one row per seed address per run. probe_tag is unique per result and is what
-- the collector searches for in the mailbox. placement is the resolved bucket; spf/dkim/dmarc
-- pass flags are parsed from the delivered message's Authentication-Results header when the
-- collector can read it (NULL = unknown / not yet observed).
--
-- Result status: pending -> sent -> (inbox | spam | missing | error).
CREATE TABLE seed_results (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    run_id      UUID        NOT NULL REFERENCES seed_runs(id) ON DELETE CASCADE,
    tenant_id   UUID        NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    address     TEXT        NOT NULL,
    provider    TEXT        NOT NULL DEFAULT 'other',
    probe_tag   TEXT        NOT NULL,
    status      TEXT        NOT NULL DEFAULT 'pending', -- pending, sent, inbox, spam, missing, error
    placement   TEXT        NOT NULL DEFAULT 'unknown', -- inbox, spam, missing, unknown
    mailbox     TEXT        NOT NULL DEFAULT '',
    spf_pass    BOOLEAN,
    dkim_pass   BOOLEAN,
    dmarc_pass  BOOLEAN,
    detail      TEXT        NOT NULL DEFAULT '',
    sent_at     TIMESTAMPTZ,
    observed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (run_id, address)
);
CREATE INDEX idx_seed_results_run ON seed_results (run_id);
CREATE INDEX idx_seed_results_tenant ON seed_results (tenant_id);

-- +goose Down
DROP TABLE IF EXISTS seed_results;
DROP TABLE IF EXISTS seed_runs;
DROP TABLE IF EXISTS seed_addresses;
DROP TABLE IF EXISTS seed_lists;
