// Command seedd is the inbox-placement / seed-list testing daemon. On each tick it advances
// every active seed run: it sends the uniquely-tagged synthetic probe messages that haven't
// been sent yet (through the configured SMTP relay), then polls the seed mailboxes over IMAP
// to record whether each probe landed in the inbox or the spam folder — or went missing after
// the collection window. Finalized results are also appended to ClickHouse for long-horizon
// placement analytics.
//
// Privacy boundary: probes are synthetic content generated by MX Sentinel, and the collector
// only ever matches our own tagged probes — no real user mail is read, stored, or logged.
//
// Config comes from MXS_SEEDTEST_* env vars (see internal/seedtest.LoadConfig). When SMTP is
// not configured seedd leaves runs pending; when a seed has no IMAP account configured its
// result stays "sent, pending" rather than being guessed. Mimics cmd/repd scaffolding.
package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/zezekim/mxsentinel/internal/config"
	"github.com/zezekim/mxsentinel/internal/obs"
	"github.com/zezekim/mxsentinel/internal/seedtest"
	chstore "github.com/zezekim/mxsentinel/internal/store/clickhouse"
	pgstore "github.com/zezekim/mxsentinel/internal/store/postgres"
)

func main() {
	intervalFlag := flag.Duration("interval", 0, "override advance interval (default from MXS_SEEDTEST_INTERVAL)")
	flag.Parse()

	if err := run(*intervalFlag); err != nil {
		fmt.Fprintln(os.Stderr, "seedd:", err)
		os.Exit(1)
	}
}

func run(intervalOverride time.Duration) error {
	cfg, err := config.Load(os.Getenv("MXS_CONFIG"))
	if err != nil {
		return err
	}
	log := obs.NewLogger("seedd", cfg.LogLevel)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	metrics := obs.NewMetrics()
	srv := obs.NewServer(cfg.HTTPAddr, metrics, log)
	srv.Start()
	defer func() {
		sctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		_ = srv.Shutdown(sctx)
	}()

	pg, err := pgstore.New(ctx, cfg.Postgres)
	if err != nil {
		return err
	}
	defer pg.Close()

	// ClickHouse is optional: placement analytics are a nice-to-have, and a run must still be
	// able to complete if the analytics store is down.
	var ch *chstore.Store
	if c, err := chstore.New(ctx, cfg.ClickHouse); err != nil {
		log.Warn("clickhouse unavailable; placement analytics disabled", "err", err)
	} else {
		ch = c
		defer ch.Close()
	}

	scfg := seedtest.LoadConfig()
	interval := scfg.Interval
	if intervalOverride > 0 {
		interval = intervalOverride
	}

	w := &worker{
		log:     log,
		pg:      pg,
		ch:      ch,
		cfg:     scfg,
		sender:  seedtest.NewSMTPSender(scfg.SMTP, nil),
		fetcher: &seedtest.NetIMAPFetcher{},
	}

	srv.SetReady(true)
	log.Info("seedd started",
		"interval", interval.String(),
		"collect_window", scfg.CollectWindow.String(),
		"smtp_configured", scfg.SMTP.Configured(),
		"imap_accounts", len(scfg.IMAPAccounts))

	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	w.tick(ctx)
	for {
		select {
		case <-ctx.Done():
			log.Info("seedd shutting down")
			return nil
		case <-ticker.C:
			w.tick(ctx)
		}
	}
}

type worker struct {
	log     *slog.Logger
	pg      *pgstore.Store
	ch      *chstore.Store
	cfg     seedtest.Config
	sender  seedtest.Sender
	fetcher seedtest.IMAPFetcher

	warnedNoSMTP bool
}

func (w *worker) tick(ctx context.Context) {
	runs, err := w.pg.ListActiveSeedRuns(ctx)
	if err != nil {
		w.log.Error("list active seed runs", "err", err)
		return
	}
	for _, run := range runs {
		if ctx.Err() != nil {
			return
		}
		switch run.Status {
		case seedtest.RunPending, seedtest.RunSending:
			w.sendRun(ctx, run)
		case seedtest.RunCollecting:
			w.collectRun(ctx, run)
		}
	}
}

// sendRun delivers every not-yet-sent probe for a run, then moves it into collection.
func (w *worker) sendRun(ctx context.Context, run pgstore.SeedRun) {
	if !w.cfg.SMTP.Configured() {
		if !w.warnedNoSMTP {
			w.log.Warn("SMTP not configured; seed runs will stay pending until MXS_SEEDTEST_SMTP_HOST is set")
			w.warnedNoSMTP = true
		}
		return
	}
	if run.Status != seedtest.RunSending {
		if err := w.pg.SetSeedRunStatus(ctx, run.ID, seedtest.RunSending); err != nil {
			w.log.Error("set run sending", "err", err, "tenant_id", run.TenantID, "run_id", run.ID)
			return
		}
	}

	from := run.FromAddress
	if from == "" {
		from = w.cfg.SMTP.From
	}
	if from == "" {
		w.log.Warn("seed run has no from address and MXS_SEEDTEST_SMTP_FROM is unset", "run_id", run.ID)
		return
	}

	pending, err := w.pg.ListSeedResultsByStatus(ctx, run.ID, seedtest.StatusPending)
	if err != nil {
		w.log.Error("list pending results", "err", err, "run_id", run.ID)
		return
	}
	now := time.Now()
	for _, res := range pending {
		if ctx.Err() != nil {
			return
		}
		probe := seedtest.BuildProbe(from, res.Address, run.RunTag, res.ProbeTag, now)
		if err := w.sender.Send(ctx, probe); err != nil {
			w.log.Warn("send probe", "err", err, "run_id", run.ID, "address", res.Address)
			_ = w.pg.MarkSeedResultError(ctx, res.ID, "send failed: "+err.Error())
			continue
		}
		if err := w.pg.MarkSeedResultSent(ctx, res.ID, time.Now()); err != nil {
			w.log.Error("mark sent", "err", err, "result_id", res.ID)
		}
	}

	counts, err := w.pg.SeedResultStatusCounts(ctx, run.ID)
	if err != nil {
		w.log.Error("status counts", "err", err, "run_id", run.ID)
		return
	}
	if counts[seedtest.StatusPending] == 0 {
		sent := counts[seedtest.StatusSent]
		if err := w.pg.MarkSeedRunCollecting(ctx, run.ID, sent); err != nil {
			w.log.Error("mark collecting", "err", err, "run_id", run.ID)
			return
		}
		w.log.Info("seed run collecting", "tenant_id", run.TenantID, "run_id", run.ID, "sent", sent)
	}
}

// collectRun polls seed mailboxes for probes and finalizes placement, completing the run once
// everything is resolved or the collection window has elapsed.
func (w *worker) collectRun(ctx context.Context, run pgstore.SeedRun) {
	sent, err := w.pg.ListSeedResultsByStatus(ctx, run.ID, seedtest.StatusSent)
	if err != nil {
		w.log.Error("list sent results", "err", err, "run_id", run.ID)
		return
	}
	windowElapsed := run.StartedAt != nil && time.Since(*run.StartedAt) > w.cfg.CollectWindow

	for _, res := range sent {
		if ctx.Err() != nil {
			return
		}
		acct, ok := w.cfg.AccountFor(res.Address)
		if !ok {
			// No IMAP credentials for this seed: leave it "sent, pending" — never guess.
			continue
		}
		collector := seedtest.NewIMAPCollector(acct, res.Provider, w.fetcher)
		cr, err := collector.Collect(ctx, res.ProbeTag)
		if err != nil {
			w.log.Warn("collect probe", "err", err, "run_id", run.ID, "address", res.Address)
			continue
		}
		if cr.Found {
			w.finalize(ctx, run, res, string(cr.Placement), cr.Placement, cr.Mailbox, cr.Auth)
			continue
		}
		if windowElapsed {
			w.finalize(ctx, run, res, seedtest.StatusMissing, seedtest.PlacementMissing, "", seedtest.AuthResults{})
		}
	}

	w.maybeComplete(ctx, run, windowElapsed)
}

// finalize writes the terminal placement to Postgres and appends an analytics row to ClickHouse.
func (w *worker) finalize(ctx context.Context, run pgstore.SeedRun, res pgstore.SeedResult, status string, placement seedtest.Placement, mailbox string, auth seedtest.AuthResults) {
	observed := time.Now()
	if err := w.pg.FinalizeSeedResult(ctx, res.ID, status, string(placement), mailbox, auth.SPF, auth.DKIM, auth.DMARC, observed); err != nil {
		w.log.Error("finalize result", "err", err, "result_id", res.ID)
		return
	}
	w.log.Info("seed result finalized", "tenant_id", run.TenantID, "run_id", run.ID,
		"address", res.Address, "placement", placement)

	if w.ch == nil {
		return
	}
	sentAt := observed
	if res.SentAt != nil {
		sentAt = *res.SentAt
	}
	listID := ""
	if run.ListID != nil {
		listID = *run.ListID
	}
	row := chstore.SeedPlacementRow{
		ResultID:   res.ID,
		RunID:      run.ID,
		TenantID:   run.TenantID,
		ListID:     listID,
		RunTag:     run.RunTag,
		Address:    res.Address,
		Provider:   res.Provider,
		IPPool:     run.IPPool,
		Placement:  string(placement),
		SPFPass:    bool01(auth.SPF),
		DKIMPass:   bool01(auth.DKIM),
		DMARCPass:  bool01(auth.DMARC),
		SentAt:     sentAt.UTC(),
		ObservedAt: observed.UTC(),
	}
	if err := w.ch.InsertSeedPlacements(ctx, []chstore.SeedPlacementRow{row}); err != nil {
		w.log.Warn("write placement analytics", "err", err, "result_id", res.ID)
	}
}

// maybeComplete transitions a run to completed when no results remain in flight, or when the
// collection window has elapsed (any still-uncollected seeds stay "sent, pending").
func (w *worker) maybeComplete(ctx context.Context, run pgstore.SeedRun, windowElapsed bool) {
	counts, err := w.pg.SeedResultStatusCounts(ctx, run.ID)
	if err != nil {
		w.log.Error("status counts", "err", err, "run_id", run.ID)
		return
	}
	inFlight := counts[seedtest.StatusPending] + counts[seedtest.StatusSent]
	if inFlight == 0 || windowElapsed {
		if err := w.pg.MarkSeedRunCompleted(ctx, run.ID); err != nil {
			w.log.Error("mark run completed", "err", err, "run_id", run.ID)
			return
		}
		w.log.Info("seed run completed", "tenant_id", run.TenantID, "run_id", run.ID)
	}
}

func bool01(b *bool) uint8 {
	if b != nil && *b {
		return 1
	}
	return 0
}
